# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Virtual env creation
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

  test:
  # This workflow contains a single job called "build"
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Flake8
        run: |
          pip install flake8
          flake8 --exclude='.venv' --extend-ignore=E501

      # Runs a set of commands using the runners shell
      - name: Pytest
        run: |
          pip install pytest-cov
          python3 -m pytest --doctest-modules --ignore=main.py --cov

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: "louis.nilbor@gmail.com"
          heroku_app_name: "excelia-exo-1"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}


